service: film-collection-manager

frameworkVersion: ">=1.1.0 <=2.43.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: serverless-admin
  environment:
    MOVIES_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MOVIES_TABLE}"

functions:
  create:
    handler: movies/create.create
    events:
      - http:
          path: movies
          method: post
          cors: true

  list:
    handler: movies/list.list
    events:
      - http:
          path: movies
          method: get
          cors: true

  get:
    handler: movies/get.get
    events:
      - http:
          path: movies/{id}
          method: get
          cors: true

  update:
    handler: movies/update.update
    events:
      - http:
          path: movies/{id}
          method: put
          cors: true

  delete:
    handler: movies/delete.delete
    events:
      - http:
          path: movies/{id}
          method: delete
          cors: true

resources:
  Resources:
    moviesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.MOVIES_TABLE}
